server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: et2301

    gateway:
      routes:
        - id: order-service
          # lb://服务名称
          uri: lb://order-service
          predicates:
            - Path=/order-system/**
            - Method=GET,POST
          filters:
            # 路由转发前去掉第一层请求
            - StripPrefix=1

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage-system/**
          filters:
            # 路由转发前去掉第一层请求
            - StripPrefix=1

        # http://localhost:9000/order-system/order/create
        # http://localhost:8080/order/create